-- Code generated by foundation abuse; DO NOT EDIT.
-- abuse-schema-version: 1
-- abuse-schema-digest: ce9156603ba7ad2632de9af56b2da6ad88ba0968f033304d81461ec38de08b28

CREATE TABLE abuse_instances (
    instance_key TEXT PRIMARY KEY,
    schema_version INTEGER NOT NULL CHECK (schema_version = 1),
    consumer TEXT NOT NULL,
    definition_version BIGINT NOT NULL CHECK (definition_version > 0),
    definition_digest TEXT NOT NULL,
    active_key_version INTEGER NOT NULL CHECK (active_key_version > 0),
    subject_secret BYTEA NOT NULL CHECK (octet_length(subject_secret) = 32),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE abuse_policy_definitions (
    instance_key TEXT NOT NULL REFERENCES abuse_instances(instance_key) ON DELETE CASCADE,
    policy_id TEXT NOT NULL,
    revision BIGINT NOT NULL CHECK (revision > 0),
    signature TEXT NOT NULL,
    definition_digest TEXT NOT NULL,
    definition JSONB NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (instance_key, policy_id)
);

CREATE TABLE abuse_meter_states (
    instance_key TEXT NOT NULL REFERENCES abuse_instances(instance_key) ON DELETE CASCADE,
    policy_id TEXT NOT NULL,
    subject_key_version INTEGER NOT NULL CHECK (subject_key_version > 0),
    subject_key BYTEA NOT NULL CHECK (octet_length(subject_key) = 32),
    state JSONB NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (instance_key, policy_id, subject_key_version, subject_key)
);

CREATE TABLE abuse_attempt_receipts (
    instance_key TEXT NOT NULL REFERENCES abuse_instances(instance_key) ON DELETE CASCADE,
    attempt_id TEXT NOT NULL,
    fingerprint BYTEA NOT NULL CHECK (octet_length(fingerprint) = 32),
    action_key TEXT NOT NULL,
    disposition TEXT NOT NULL CHECK (disposition IN ('allow', 'challenge', 'reject')),
    resolved_outcome TEXT NOT NULL DEFAULT '',
    default_outcome TEXT NOT NULL DEFAULT '',
    pending_until TIMESTAMPTZ,
    record JSONB NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (instance_key, attempt_id)
);

CREATE INDEX abuse_meter_states_expiry
    ON abuse_meter_states (instance_key, expires_at);
CREATE INDEX abuse_attempt_receipts_expiry
    ON abuse_attempt_receipts (instance_key, expires_at);
CREATE INDEX abuse_attempt_receipts_pending
    ON abuse_attempt_receipts (instance_key, pending_until)
    WHERE disposition = 'allow' AND resolved_outcome = '' AND default_outcome <> '';
