-- Code generated by foundation abuse; DO NOT EDIT.
-- abuse-schema-version: 1
-- abuse-schema-digest: ce9156603ba7ad2632de9af56b2da6ad88ba0968f033304d81461ec38de08b28

DROP TABLE IF EXISTS abuse_attempt_receipts;
DROP TABLE IF EXISTS abuse_meter_states;
DROP TABLE IF EXISTS abuse_policy_definitions;
DROP TABLE IF EXISTS abuse_instances;
