-- Code generated by foundation privacy; DO NOT EDIT.
-- privacy-schema-version: 1
-- privacy-schema-digest: edfe30c5db8351b442205e1576189873a785ce25be8178500bdab62b5085e182

DROP TABLE IF EXISTS privacy_host_receipts;
DROP TABLE IF EXISTS privacy_host_commands;
DROP TABLE IF EXISTS privacy_owner_receipts;
DROP TABLE IF EXISTS privacy_owner_tasks;
DROP TABLE IF EXISTS privacy_rights_requests;
DROP TABLE IF EXISTS privacy_retention_items;
DROP TABLE IF EXISTS privacy_evidence_events;
DROP TABLE IF EXISTS privacy_command_receipts;
DROP TABLE IF EXISTS privacy_definition_revisions;
DROP TABLE IF EXISTS privacy_instances;
