-- Code generated by foundation work; DO NOT EDIT.
-- work-schema-version: 1
-- work-schema-digest: b067f8cfd0161703c1f7f1ad8fba521eab1444fabe50d546880966eb0d99aef7

DROP TABLE IF EXISTS work_schedules;
DROP TABLE IF EXISTS work_attempts;
DROP TABLE IF EXISTS work_jobs;
DROP TABLE IF EXISTS work_instances;
