-- Code generated by foundation work; DO NOT EDIT.
-- work-schema-version: 1
-- work-schema-digest: b067f8cfd0161703c1f7f1ad8fba521eab1444fabe50d546880966eb0d99aef7

CREATE TABLE work_instances (
    instance_key TEXT PRIMARY KEY,
    schema_version INTEGER NOT NULL CHECK (schema_version = 1),
    catalog_version BIGINT NOT NULL CHECK (catalog_version > 0),
    catalog_digest TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE work_jobs (
    instance_key TEXT NOT NULL REFERENCES work_instances(instance_key) ON DELETE CASCADE,
    job_id UUID NOT NULL,
    kind TEXT NOT NULL,
    queue TEXT NOT NULL,
    status TEXT NOT NULL CHECK (
        status IN ('queued', 'running', 'retrying', 'paused', 'succeeded', 'failed', 'cancelled')
    ),
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    progress JSONB,
    result JSONB,
    result_summary TEXT NOT NULL DEFAULT '',
    last_error TEXT NOT NULL DEFAULT '',
    attempt INTEGER NOT NULL DEFAULT 0 CHECK (attempt >= 0),
    max_attempts INTEGER NOT NULL CHECK (max_attempts > 0),
    priority INTEGER NOT NULL DEFAULT 0 CHECK (priority BETWEEN -1000 AND 1000),
    run_at TIMESTAMPTZ NOT NULL,
    fingerprint BYTEA NOT NULL CHECK (octet_length(fingerprint) = 32),
    idempotency_key TEXT NOT NULL DEFAULT '',
    replay_of UUID,
    paused_from TEXT NOT NULL DEFAULT '',
    lease_token UUID,
    lease_owner TEXT NOT NULL DEFAULT '',
    lease_expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    cancelled_at TIMESTAMPTZ,
    PRIMARY KEY (instance_key, job_id),
    CHECK (
        (status = 'running' AND lease_token IS NOT NULL AND lease_owner <> '' AND lease_expires_at IS NOT NULL)
        OR
        (status <> 'running' AND lease_token IS NULL AND lease_owner = '' AND lease_expires_at IS NULL)
    ),
    CHECK (attempt <= max_attempts),
    CHECK (
        (status IN ('succeeded', 'failed', 'cancelled') AND finished_at IS NOT NULL)
        OR
        (status NOT IN ('succeeded', 'failed', 'cancelled') AND finished_at IS NULL)
    )
);

CREATE UNIQUE INDEX work_jobs_idempotency_unique
    ON work_jobs (instance_key, idempotency_key)
    WHERE idempotency_key <> '';

CREATE INDEX work_jobs_due_claim_idx
    ON work_jobs (instance_key, queue, priority DESC, run_at, created_at, job_id)
    WHERE status IN ('queued', 'retrying');

CREATE INDEX work_jobs_expired_lease_idx
    ON work_jobs (instance_key, lease_expires_at)
    WHERE status = 'running';

CREATE INDEX work_jobs_operations_idx
    ON work_jobs (instance_key, status, kind, queue, created_at DESC);

CREATE INDEX work_jobs_replay_idx
    ON work_jobs (instance_key, replay_of)
    WHERE replay_of IS NOT NULL;

CREATE INDEX work_jobs_retention_idx
    ON work_jobs (instance_key, finished_at)
    WHERE status IN ('succeeded', 'failed', 'cancelled');

CREATE TABLE work_attempts (
    instance_key TEXT NOT NULL,
    job_id UUID NOT NULL,
    attempt_number INTEGER NOT NULL CHECK (attempt_number > 0),
    worker_id TEXT NOT NULL,
    outcome TEXT NOT NULL CHECK (
        outcome IN ('running', 'succeeded', 'retrying', 'failed', 'cancelled', 'paused', 'lease_expired')
    ),
    error TEXT NOT NULL DEFAULT '',
    started_at TIMESTAMPTZ NOT NULL,
    finished_at TIMESTAMPTZ,
    PRIMARY KEY (instance_key, job_id, attempt_number),
    FOREIGN KEY (instance_key, job_id)
        REFERENCES work_jobs(instance_key, job_id) ON DELETE CASCADE,
    CHECK (
        (outcome = 'running' AND finished_at IS NULL)
        OR
        (outcome <> 'running' AND finished_at IS NOT NULL)
    )
);

CREATE INDEX work_attempts_history_idx
    ON work_attempts (instance_key, job_id, attempt_number);

CREATE TABLE work_schedules (
    instance_key TEXT NOT NULL REFERENCES work_instances(instance_key) ON DELETE CASCADE,
    schedule_key TEXT NOT NULL,
    next_run_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (instance_key, schedule_key)
);

CREATE INDEX work_schedules_due_idx
    ON work_schedules (instance_key, next_run_at);
